#!/bin/bash

if [[ -L $HOME/.config/sway && -d $HOME/.config/sway ]]; then
    echo "Remaking sway link"
    rm $HOME/.config/sway
    ln -s $PWD $HOME/.config/sway
fi

cd plugins
for folder in *; do
    if [ -d $PWD/$folder ]; then
        echo -n "Plugin ${folder}..."
        #echo $folder
        if [[ -L $HOME/.config/$folder && -d $HOME/.config/$folder ]]; then
            echo -n "deleting link..."
            rm $HOME/.config/$folder
        fi
        echo "making link"
        ln -s $PWD/$folder $HOME/.config/$folder
    fi
done
